#!/bin/sh

# plot tcp_probe data 
tempf=$PATH_TRANSLATED

f=`mktemp -t f.XXXXXX` || echo "can't create temp file"
zcat $tempf > $f || cp $tempf $f

echo Content-type: image/png
echo ""

#first get list of unique destination ip and ports
flow_ids=`grep -v -i "#" $f | cut -d ' ' -f 3 | sort | uniq `

#now sort tcp_probe output for gnuplot
temp=`mktemp -t probe.XXXXXX` || echo "can't create temp file"
tput=`mktemp -t tput.XXXXX` || echo "can't create temp file"
rtt=`mktemp -t rtt.XXXXX` || echo "can't create temp file" 
comma=''; plot='plot '; plotrtt='plot '
j=0
for i in $flow_ids; do
   grep -i $i $f >> $temp
   echo -e '\n\n' >>$temp
   plot="$plot $comma '$temp' index $j u 1:7 w l title 'flow $j cwnd', '$tput' index $j u 1:2 w p axes x1y2 title 'flow $j tput'"
   plotrtt="$plotrtt $comma '$temp' index $j u 1:10 w l title 'flow $j srtt'"
   comma=","
   ((j++))
done

rttfile=`echo $tempf | sed -e 's/\.probe/\.ping/'`
if [  -e $rttfile ]; then
	cut -f 8 -d ' ' $rttfile | cut -f 2 -d '=' >$rtt
	plotping="plot \"$rtt\" title \"ping time\" "
else
    	plotping=""
fi

# get throughput from packet sequence numbers
awk --non-decimal-data 'BEGIN {t=-1; dt=1} {if (NF < 6) printf "\n\n"; else {seq=$6; if (t<0 || t>$1) {t=$1; lastseq=seq}; if ($1-t >= dt) {print $1, (seq-lastseq)*8/1024/1024/($1-t); t=$1; lastseq=seq}} } ' $temp > $tput

title1=`grep -i "#" $f | sed -n '1p' | sed -e 's/#//'`
title2=`grep -i "#" $f | sed -n '2p' | sed -e 's/#//'`

gnuplot <<EOF
set xlabel "time (seconds)"
set ylabel "cwnd (packets)"
set y2label "throughput (Mbps)"
set ytics nomirror
set y2range [0:]
set y2tics
#set xrange [0:100]
#set title "$j flows, ${3}Mbps, ${2}ms latency, Q ${4} xBDP, test ${6}"
set title "$title1 \n $title2"
set terminal png 
set size 1,2
set origin 0,0
set multiplot

set size 1, 0.95
set origin 0, 1 
$plot

set size 1,0.95
set origin 0, 0
set xlabel "time (seconds)"
set ylabel "srtt (ms)"
set title ""
#$plotrtt

set ylabel 'ping time (ms)'
$plotping

unset multiplot

EOF

rm $f $temp $tput $rttfile

