#!/bin/bash

# load libraries
LIB_PATH="$(dirname $0)/../lib"

source $LIB_PATH/io
PLOTS_HORIZONTAL_SIZE=700
PLOTS_GOLDEN_RATIO=1.61803399
PLOTS_EPS_WHITE_BLACK_PLOT_SUFFIX=bw.eps
PLOTS_EPS_COLOR_PLOT_SUFFIX=color.eps
PLOTS_PLOT_DATAFILE_SUFFIX=data
PLOTS_DEFAULT_POINTSIZE=1

plots_generate_index_file()
{
	local dir=$1
	local html=$dir/index.html
	verbose "Generating $html"
	cat <<- EOF > $html
		<html><body>
		Click image to see its data file
		<br />
		EOF
	for i in $(cd $dir && find -name '*png' | sort -n -t t -k 9,9n)
	do
		local filename_prefix=$(echo $i| sed 's/\.png//g')
		cat <<- EOF >> $html
			<div>
			<a href='$filename_prefix.$PLOTS_PLOT_DATAFILE_SUFFIX'><img align=center src='$i' alt='$i' /></a>
			<a href='$filename_prefix.$PLOTS_EPS_WHITE_BLACK_PLOT_SUFFIX'>Black White EPS</a>
			<a href='$filename_prefix.$PLOTS_EPS_COLOR_PLOT_SUFFIX'>Color EPS</a>
			</div>
			EOF
	done
	echo "</html></body>" >> $html
}

plots_get_plot_vertical_size()
{
	echo $PLOTS_HORIZONTAL_SIZE/$PLOTS_GOLDEN_RATIO | bc
}

plots_get_plot_size()
{
	local size=$1 # double_vertical double_horizontal double or none
	local horiz=$PLOTS_HORIZONTAL_SIZE
	local vert=$(plots_get_plot_vertical_size)
	case $size in 
		double_horizontal)
			horiz=$(echo $horiz*2 | bc)
		;;
		double_vertical)
			vert=$(echo $vert*2 | bc)
		;;
		double)
			horiz=$(echo $horiz*2 | bc)
			vert=$(echo $vert*2 | bc)
		;;
	esac
	echo "$horiz,$vert"
}

plots_get_zoom_plot_size()
{
	local percentage=$1
	local horiz=$PLOTS_HORIZONTAL_SIZE
	local vert=$(plots_get_plot_vertical_size)
	echo "$(echo "$horiz*$percentage/100" | bc),$(echo "$vert*$percentage/100" | bc)"
}

plots_replot_eps()
{
	local filename_prefix=$1
	cat <<- EOF
		set term postscript eps enhanced
		set output "$filename_prefix.$PLOTS_EPS_WHITE_BLACK_PLOT_SUFFIX"
		replot

		set term postscript eps color enhanced
		set output "$filename_prefix.$PLOTS_EPS_COLOR_PLOT_SUFFIX"
		replot
		EOF
}

# will return notheing if size is not supplied
# this will make the plot use the default size
plots_pointsize_command()
{
	local size=${1:-$PLOTS_DEFAULT_POINTSIZE}
	echo "set pointsize $size"
}

