#!/bin/bash

# Globals
CLIENT_NAME_PREFIX="client"

run_command_on_client()
{
	local user=$1
	local host=$2
	local command=$3
	verbose "executing '$command' on client $host"
	verbose "$host $(ssh $user@$host "$command")" "-e"
}

copy_file_to_host()
{
	local user=$1
	local host=$2
	local file=$3
	verbose "copying file $file to $host"
	verbose "$(scp $file $user@$host:/tmp)"
}

copy_file_from_host()
{
	local user=$1
	local host=$2
	local src=$3
	local dst=$4
	verbose "copying file $user@$host:$src to $dst"
	verbose "$(scp $file $user@$host:$src $dst)"
}

delete_file_on_host()
{
	local host=$1
	local file=$2
	verbose "Deleting file $file from $host"
	ssh root@$host "rm -f $file" > /dev/null
}

run_command_on_all_clients()
{
	local user=$1
	local command=$2
	local pids=
	for c in $CLIENTS
	do
		run_command_on_client $user "$CLIENT_NAME_PREFIX$c" "$command" &
		pids="$pids $(echo $!)"
	done
	# wait for jobs to finish
	for p in $pids
	do
		verbose "waiting for command to finish - pid $p"
		wait $p
	done
}
