#!/bin/bash

# Globals
CLIENT_NAME_PREFIX="client"

remote_run_command_on_client()
{
	local user=$1
	local host=$2
	local command=$3
	verbose "executing '$command' on client $host"
	verbose "$host $(ssh $user@$host "$command")" "-e"
}

remote_load_kernel_module_on_client()
{
	local host=$1
	local module=$2
	verbose "loading '$module' on client $host"
	verbose "$host $(ssh root@$host "modprobe $module")" "-e"
}

remote_copy_file_to_host()
{
	local user=$1
	local host=$2
	local file=$3
	verbose "copying file $file to $host"
	scp $file $user@$host:/tmp > /dev/null
}

remote_copy_file_from_host()
{
	local user=$1
	local host=$2
	local src=$3
	local dst=$4
	verbose "copying file $user@$host:$src to $dst"
	scp $file $user@$host:$src $dst > /dev/null
}

remote_delete_file_on_host()
{
	local host=$1
	local file=$2
	verbose "Deleting file $file from $host"
	ssh root@$host "rm -f $file" > /dev/null
}

remote_run_command_on_all_clients()
{
	local user=$1
	local command=$2
	local pids=
	for c in $CLIENTS
	do
		remote_run_command_on_client $user "$CLIENT_NAME_PREFIX$c" "$command" &
		pids="$pids $(echo $!)"
	done
	# wait for jobs to finish
	for p in $pids
	do
		verbose "waiting for command to finish - pid $p"
		wait $p
	done
}
