#!/bin/bash

source $LIB_PATH/io
source $LIB_PATH/remote

# Globals
WIRELESS_ATHEROS_ABOLT=0
WIRELESS_TXPOWER_MIN=1

wireless_atheros_set_no_accel_to_network()
{
	verbose "set on all clients and ap atheros no accell flags"
	run_command_on_all_clients root "iwpriv ath0 abolt $WIRELESS_ATHEROS_ABOLT && echo -n set atheros no acceleration"
	run_command_on_client root ap "iwpriv ath1 abolt $WIRELESS_ATHEROS_ABOLT && echo -n set atheros no acceleration"
}

wireless_set_all_clients_minimum_txpower()
{
	verbose "set on all clients txpower = 1dBm"
	run_command_on_all_clients root "iwconfig ath0 txpower $WIRELESS_TXPOWER_MIN 2>/dev/null && echo -n set clients to txpower=${WIRELESS_TXPOWER_MIN} dBm"
}
