#!/bin/bash 

# Globals
OPTS_ARGS="$@"
OPTS_START=1

opts_check_for_no_opts()
{
	# exit if no arguments
	if [[ -z $OPTS_ARGS ]]
	then 
		usage
		exit 1
	fi
}

opts_check_clients_opts()
{
	# or clients list or end number of clients
	if [[ -z $END && -z $CLIENTS ]]
	then 
		error "You should provide -n or -c"
		echo 
		usage
		exit 1
	fi
}

opts_combine_clients_opts()
{
	if [[ ! -z $END ]]; then
		# we got -n, so we'll convert to $CLIENTS
		CLIENTS=`seq -s ' ' $OPTS_START $END`
	fi
}

opts_get_clients_list()
{
	local clients=$1 # expects 1,2,3,4
	echo $clients | tr ',' ' '
}

# check that we got just one command line variable.
# example: -c 1 and not -c 1,2,3
opts_check_for_one_input()
{
	local input="$@"
	local num=$(echo $input | wc --words)
	[[ $num -eq 1 ]] && echo $num
}
