#!/bin/bash

# load libraries
LIB_PATH="$(dirname $0)/../lib"

source $LIB_PATH/io

# Globals
CLIENT_NAME_PREFIX="client"
REMOTE_KMSG_TMP_FILE=/tmp/kmsg
REMOTE_KMSG_FILE_SUFFIX=.kmsg

remote_run_command_on_client()
{
	local user=$1
	local host=$2
	local command=$3
	debug "Executing '$command' on $host"
	ssh $user@$host "$command"
}

remote_remove_kernel_module_on_client()
{
	local host=$1
	local module=$2
	debug "removing kernel module '$module' on $host"
	remote_run_command_on_client root $host "rmmod $module 2>&1 > /dev/null"
}

remote_load_kernel_module_on_client()
{
	local host=$1
	local module=$2
	debug "loading '$module' on $host"
	remote_remove_kernel_module_on_client $host $module
	remote_run_command_on_client root $host "modprobe $module"
	remote_check_if_module_is_loaded $host $module
	[[ -z $(remote_check_if_module_is_loaded $host $module) ]] \
		&& io_exit_with_error "can't load module $module"
}

remote_check_if_module_is_loaded()
{
	local host=$1
	local module=$2
	local ret=$(remote_run_command_on_client root $host "lsmod | grep $module" 2>&1 /dev/null)
	if [[ -z $ret ]]
	then
		debug "module $module is not loaded on $host"
	else
		debug "module $module already loaded on $host"
	fi
	echo $ret
}

remote_copy_file_to_host()
{
	local user=$1
	local host=$2
	local file=$3
	verbose "copying file $file to $host"
	scp $file $user@$host:/tmp > /dev/null
}

remote_copy_file_from_host()
{
	local user=$1
	local host=$2
	local src=$3
	local dst=$4
	debug "copying file $user@$host:$src to $dst"
	scp $file $user@$host:$src $dst > /dev/null
}

remote_delete_file_on_host()
{
	local host=$1
	local file=$2
	debug "Deleting file $file from $host"
	ssh root@$host "rm -f $file" > /dev/null
}

remote_run_command_on_all_clients()
{
	local user=$1
	local command=$2
	local pids=
	for c in $CLIENTS
	do
		local client=$c
		# check if client is a number or a word like ap,src...
		[[ $c < "a" ]] && client="$CLIENT_NAME_PREFIX$c"
		remote_run_command_on_client $user $client "$command" &
		pids="$pids $!"
	done
	wait_for_pids $pids
}

remote_start_kmsg_logging()
{
	local host=$1
	verbose "Log kernel messages on $host"
	remote_run_command_on_client root $host "cat /proc/kmsg > /dev/null  & pid=\$! && sleep 1 && kill \$pid && cat /proc/kmsg  | $IO_COMPRESS_COMMAND > $REMOTE_KMSG_TMP_FILE" &
}

remote_stop_kmsg_logging()
{
	local host=$1
	local destdir=$2
	local dst_file="$REMOTE_KMSG_TMP_FILE $destdir/$host$REMOTE_KMSG_FILE_SUFFIX"
	verbose "Stop kernel messages logging on $host"
	remote_kill $host "/proc/kmsg"
	remote_copy_file_from_host root $host $dst_file
	remote_delete_file_on_host $host $REMOTE_KMSG_TMP_FILE
}

remote_network_interface_reset()
{
	local host=$1
	local iface=$2
	verbose "Reloading interface $iface on $host"
	remote_run_command_on_client root $host "ifdown $iface" 2> /dev/null
	remote_run_command_on_client root $host "ifup $iface" 2> /dev/null
	sleep 1
}

remote_kill()
{
	local host=$1
	local exp=$2 # expression for grep to identify the proccess to kill
	debug "killing all '$exp' on $host"
	remote_run_command_on_client root $host "kill \$(ps fax | grep '$exp' | awk '{print \$1}') 2> /dev/null"
}
